modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "CC0"
issueTrackerURL = "https://github.com/Fabricators-of-Create/create-fabric-addon-template"

[[mods]]
modId = "betteradminshop"
version = "${mod_version_full}"
displayName = "Create: Better Admin Shop"
authors = "ChristemDc"
description = '''
Addon de Create que añade un puesto de tienda de administrador. Configura slots de venta y de compra (con precios de hasta dos ítems, cantidad por transacción e ítem visible personalizado), con stock por jugador y reabastecimiento cada 24 h. Las compras se entregan en paquetes de Create en la zona de entrega. Incluye un panel de administración con arrastrar y soltar, copiar/pegar de slots y registros de transacciones en SQLite, con espejo opcional a MongoDB para gestión externa.
'''
logoFile = "icon.png"

[[dependencies.betteradminshop]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.betteradminshop]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.betteradminshop]]
modId = "create"
type = "required"
versionRange = "${create_version_range}"
ordering = "AFTER"
side = "BOTH"
